export const language = {
  //FORMS
  field_error_required: "Поле должно быть заполнено!",
  field_error_max_length: "Макс. кол-во символов - ",
  field_error_min_length: "Мин. кол-во символов - ",
  field_error_email: "Эл. адрес имеет неверный формат!",
  field_date_picker_submit_title: "Выбрать дату",
  field_time_picker_submit_title: "Выбрать время",
  field_age_name: "Дата рождения",
  btn_accept: "Принять",
  btn_cancel: "Отмена",
  date_picker_header: "Выбор даты",
  years_ago: "лет",
  submit_button_title: "Авторизация",
  register_button_title: "Регистрация",
  remember_button_title: "Забыли пароль?",
  theme_dark: "Темная тема",
  theme_light: "Светлая тема",
  theme_system: "Системная тема",
  theme_settings: "Настройки темы:",
};
